# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ws_discovery.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12ws_discovery.proto\x12\x0bwsdiscovery\"\x13\n\x11GetNvtListRequest\")\n\x12GetNvtListResponse\x12\x13\n\x0bnvt_address\x18\x01 \x03(\t2c\n\x12WsDiscoveryService\x12M\n\nGetNvtList\x12\x1e.wsdiscovery.GetNvtListRequest\x1a\x1f.wsdiscovery.GetNvtListResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ws_discovery_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETNVTLISTREQUEST._serialized_start=35
  _GETNVTLISTREQUEST._serialized_end=54
  _GETNVTLISTRESPONSE._serialized_start=56
  _GETNVTLISTRESPONSE._serialized_end=97
  _WSDISCOVERYSERVICE._serialized_start=99
  _WSDISCOVERYSERVICE._serialized_end=198
# @@protoc_insertion_point(module_scope)
